config: !!python/object:__main__.LightningTrainingConfig
  batch_size: 32
  device_id: demo_device_1
  dropout_rate: 0.1
  hidden_dim: 128
  input_dim: 50
  learning_rate: 0.001
  num_classes: 5
  num_epochs: 10
  num_samples: 2000
  replica_id: demo_replica_1
