# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: torchLoom/torchLoom.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'torchLoom/torchLoom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19torchLoom/torchLoom.proto\"9\n\x0eRegisterDevice\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\t\"!\n\nDrainEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\"&\n\x10ReplicaFailEvent\x12\x12\n\nreplica_id\x18\x01 \x01(\t\")\n\x12MonitoredFailEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\"\x1f\n\x11ResetLearningRate\x12\n\n\x02lr\x18\x01 \x01(\t\"\x85\x01\n\x11\x43hangeConfigEvent\x12;\n\rconfig_params\x18\x01 \x03(\x0b\x32$.ChangeConfigEvent.ConfigParamsEntry\x1a\x33\n\x11\x43onfigParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb2\x02\n\rEventEnvelope\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x10\n\x08ts_nanos\x18\x02 \x01(\x04\x12*\n\x0fregister_device\x18\t \x01(\x0b\x32\x0f.RegisterDeviceH\x00\x12\x1c\n\x05\x64rain\x18\n \x01(\x0b\x32\x0b.DrainEventH\x00\x12)\n\x0creplica_fail\x18\x0b \x01(\x0b\x32\x11.ReplicaFailEventH\x00\x12-\n\x0emonitored_fail\x18\x0c \x01(\x0b\x32\x13.MonitoredFailEventH\x00\x12+\n\rlearning_rate\x18\x0e \x01(\x0b\x32\x12.ResetLearningRateH\x00\x12)\n\x0b\x63onfig_info\x18\x0f \x01(\x0b\x32\x12.ChangeConfigEventH\x00\x42\x06\n\x04\x62ody\"@\n\x15\x44\x65viceReplicaMapEntry\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'torchLoom.torchLoom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGECONFIGEVENT_CONFIGPARAMSENTRY']._loaded_options = None
  _globals['_CHANGECONFIGEVENT_CONFIGPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_REGISTERDEVICE']._serialized_start=29
  _globals['_REGISTERDEVICE']._serialized_end=86
  _globals['_DRAINEVENT']._serialized_start=88
  _globals['_DRAINEVENT']._serialized_end=121
  _globals['_REPLICAFAILEVENT']._serialized_start=123
  _globals['_REPLICAFAILEVENT']._serialized_end=161
  _globals['_MONITOREDFAILEVENT']._serialized_start=163
  _globals['_MONITOREDFAILEVENT']._serialized_end=204
  _globals['_RESETLEARNINGRATE']._serialized_start=206
  _globals['_RESETLEARNINGRATE']._serialized_end=237
  _globals['_CHANGECONFIGEVENT']._serialized_start=240
  _globals['_CHANGECONFIGEVENT']._serialized_end=373
  _globals['_CHANGECONFIGEVENT_CONFIGPARAMSENTRY']._serialized_start=322
  _globals['_CHANGECONFIGEVENT_CONFIGPARAMSENTRY']._serialized_end=373
  _globals['_EVENTENVELOPE']._serialized_start=376
  _globals['_EVENTENVELOPE']._serialized_end=682
  _globals['_DEVICEREPLICAMAPENTRY']._serialized_start=684
  _globals['_DEVICEREPLICAMAPENTRY']._serialized_end=748
# @@protoc_insertion_point(module_scope)
